config/routes.rb
Trucking::Application.routes.draw do
  devise_for :users
  resources :users

  resources :routes

  resources :drivers

  
  root 'home#index'

  get 'home/about' => 'home#about'
  get 'home/contact' => 'home#contact'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :routes
  validates :name, :presence => true
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :driver
  %i/advance_cents reimbursement_cents gross_revenue_cents net_revenue_cents trailer_rental_cents/.each do |column|
    monetize column, with_currency: :USD
  end

  def attributes_to_display
    attrs = {}
    %w/trip_number date advance reimbursement gross_revenue net_revenue trailer_rented trailer_rental/.each do |att|
      attrs[att] = self.send att
    end
    attrs

    # Blacklisting
    # cents to money
    # attrs = attributes.
    #   except(*%w/id created_at updated_at/)
    # monies = []
    # attrs.each do |key,val| 
    #   if att = key[/(.+)_cents/,1]
    #     monies << att 
    #   end
    # end
    # monies.each{|att| attrs[att] = self.send att}
    # attrs.reject! do |key,val| 
    #   key.include? '_cents' or key.include? '_currency'
    # end
  end

  def trailer_rented_str
    trailer_rented? ? 'Yes' : 'No'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :authenticate_user!
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render action: 'show', status: :created, location: @driver }
      else
        format.html { render action: 'new' }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render action: 'show', status: :created, location: @route }
      else
        format.html { render action: 'new' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:date, :trip_number, :advance, :reimbursement, :gross_revenue, :net_revenue, :driver_id, :trailer_rented, :trailer_rental)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
  def route_display_value(value)
    case value
    when Money
      humanized_money_with_symbol(value)
    when TrueClass, FalseClass
      value ? 'Yes' : 'No'
    else 
      value
    end
  end
  
  def display_route_attribute(value)
    value.titleize
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drivers/_form.html.haml
= form_for @driver, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), drivers_path, :class => 'btn'

app/views/drivers/edit.html.haml
- model_class = Driver
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/drivers/index.html.haml
- model_class = Driver
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @drivers.each do |driver|
      %tr
        %td= link_to driver.id, driver_path(driver)
        %td= driver.name
        %td=l driver.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_driver_path(driver), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), driver_path(driver), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_driver_path, :class => 'btn btn-primary'

app/views/drivers/new.html.haml
- model_class = Driver
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/drivers/show.html.haml
- model_class = Driver
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @driver.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), drivers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_driver_path(@driver), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), driver_path(@driver), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/home/about.html.haml
#h1 HI MISTY

app/views/home/contact.html.haml
#h1 JACE RYAN

app/views/home/index.html.haml
#h1 Hello World!

app/views/layouts/_signin.html.haml
%ul.nav.pull-right
  - if current_user 
    %li
      = link_to drivers_path do
        = fa_icon 'automobile'
        Drivers
    %li
      = link_to routes_path do
        = fa_icon 'exchange'
        Routes
    %li
      = link_to destroy_user_session_path, method: :delete do
        = fa_icon 'sign-out'
        Sign out
  - else
    %li
      = link_to new_user_session_path do
        = fa_icon 'sign-in'
        Sign in

app/views/layouts/application.html.haml
!!! 5

%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : Trucking::NAME
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href='/') #{Trucking::NAME}
          .container.nav-collapse
            %ul.nav
              %li= link_to "Home", "/"
              %li= link_to "About", "/home/about"
              %li.right= link_to "Contact", "/home/contact"
            = render('layouts/signin')

    .container-fluid

      .row-fluid
        .span8.offset2
          = bootstrap_flash
          = yield
        -# .span2
          = render ('layouts/toolbar') if current_user
    
      %footer
        %p &copy; #{Trucking::NAME} 2014

app/views/routes/_form.html.haml
= form_for @route, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :date, :class => 'control-label'
    .controls
      = f.date_field :date, :class => 'date_field'
  .control-group
    = f.label :trip_number, :class => 'control-label'
    .controls
      = f.text_field :trip_number, :class => 'text_field'
  .control-group
    = f.label :advance, :class => 'control-label'
    .controls
      = f.text_field :advance, :class => 'text_field'
  .control-group
    = f.label :reimbursement, :class => 'control-label'
    .controls
      = f.text_field :reimbursement, :class => 'text_field'
  .control-group
    = f.label :gross_revenue, :class => 'control-label'
    .controls
      = f.text_field :gross_revenue, :class => 'text_field'
  .control-group
    = f.label :net_revenue, :class => 'control-label'
    .controls
      = f.text_field :net_revenue, :class => 'text_field'
  .control-group
    = f.label :driver_id, :class => 'control-label'
    .controls
      = f.collection_select :driver_id, Driver.all, :id, :name, :class => 'text_field'
  .control-group
    = f.label :trailer_rented, :class => 'control-label'
    .controls
      = f.check_box :trailer_rented, :class => 'check_box'
  .control-group
    = f.label :trailer_rental, :class => 'control-label'
    .controls
      = f.text_field :trailer_rental, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), routes_path, :class => 'btn'

app/views/routes/edit.html.haml
- model_class = Route
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/routes/index.html.haml
- model_class = Route
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      -# %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:date)
      %th= model_class.human_attribute_name(:trip_number)
      %th= model_class.human_attribute_name(:advance)
      %th= model_class.human_attribute_name(:reimbursement)
      %th= model_class.human_attribute_name(:gross_revenue)
      %th= model_class.human_attribute_name(:net_revenue)
      %th Driver
      %th= model_class.human_attribute_name(:trailer_rented)
      %th= model_class.human_attribute_name(:trailer_rental)
      -# %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @routes.each do |route|
      %tr
        -# %td= link_to route.id, route_path(route)
        %td= route.date
        %td= link_to route.trip_number, route_path(route)
        %td= humanized_money_with_symbol route.advance
        %td= humanized_money_with_symbol route.reimbursement
        %td= humanized_money_with_symbol route.gross_revenue
        %td= humanized_money_with_symbol route.net_revenue
        %td= link_to route.driver.name, driver_path(route.driver.id)
        %td= route.trailer_rented_str
        %td= humanized_money_with_symbol route.trailer_rental
        -# %td=l route.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_route_path(route), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), route_path(route), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_route_path, :class => 'btn btn-primary'

app/views/routes/new.html.haml
- model_class = Route
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/routes/show.html.haml
.page-header
  %h1= "Route ##{@route.trip_number}"
  %h3
    Driver:
    = link_to @route.driver.name, driver_path(@route.driver)

%table.table.table-striped
  %tbody
    -@route.attributes_to_display.each do |key, value|
      %tr
        %td= display_route_attribute(key)
        %td= route_display_value(value)
        
























-# - model_class = Route
-# .page-header
-#   %h1=t '.title', :default => model_class.model_name.human.titleize
-#
-# %p
-#   %strong= model_class.human_attribute_name(:date) + ':'
-#   %br
-#   = @route.date
-# %p
-#   %strong= model_class.human_attribute_name(:trip_number) + ':'
-#   %br
-#   = @route.trip_number
-# %p
-#   %strong= model_class.human_attribute_name(:advance) + ':'
-#   %br
-#   = humanized_money_with_symbol @route.advance
-# %p
-#   %strong= model_class.human_attribute_name(:reimbursement) + ':'
-#   %br
-#   = humanized_money_with_symbol @route.reimbursement
-# %p
-#   %strong= model_class.human_attribute_name(:gross_revenue) + ':'
-#   %br
-#   = humanized_money_with_symbol @route.gross_revenue
-# %p
-#   %strong= model_class.human_attribute_name(:net_revenue) + ':'
-#   %br
-#   = humanized_money_with_symbol @route.net_revenue
-# %p
-#   %strong Driver
-#   %br
-#   = link_to @route.driver.name, driver_path(@route.driver.id)
-# %p
-#   %strong= model_class.human_attribute_name(:trailer_rented) + ':'
-#   %br
-#   = @route.trailer_rented_str
-# %p
-#   %strong= model_class.human_attribute_name(:trailer_rental) + ':'
-#   %br
-#   = humanized_money_with_symbol @route.trailer_rental
-#
-# .form-actions
-#   = link_to t('.back', :default => t("helpers.links.back")), routes_path, :class => 'btn'
-#   = link_to t('.edit', :default => t("helpers.links.edit")), edit_route_path(@route), :class => 'btn'
-#   = link_to t('.destroy', :default => t("helpers.links.destroy")), route_path(@route), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :username, :class => 'control-label'
    .controls
      = f.text_field :username, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'text_field'
  .control-group
    = f.label :admin, :class => 'control-label'
    .controls
      = f.text_field :admin, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :encrypted_password, :class => 'control-label'
    .controls
      = f.text_field :encrypted_password, :class => 'text_field'
  .control-group
    = f.label :reset_password_token, :class => 'control-label'
    .controls
      = f.text_field :reset_password_token, :class => 'text_field'
  .control-group
    = f.label :reset_password_sent_at, :class => 'control-label'
    .controls
      = f.text_field :reset_password_sent_at, :class => 'text_field'
  .control-group
    = f.label :remember_created_at, :class => 'control-label'
    .controls
      = f.text_field :remember_created_at, :class => 'text_field'
  .control-group
    = f.label :current_sign_in_at, :class => 'control-label'
    .controls
      = f.text_field :current_sign_in_at, :class => 'text_field'
  .control-group
    = f.label :last_sign_in_at, :class => 'control-label'
    .controls
      = f.text_field :last_sign_in_at, :class => 'text_field'
  .control-group
    = f.label :current_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :current_sign_in_ip, :class => 'text_field'
  .control-group
    = f.label :last_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :last_sign_in_ip, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:password)
      %th= model_class.human_attribute_name(:admin)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:encrypted_password)
      %th= model_class.human_attribute_name(:reset_password_token)
      %th= model_class.human_attribute_name(:reset_password_sent_at)
      %th= model_class.human_attribute_name(:remember_created_at)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:current_sign_in_ip)
      %th= model_class.human_attribute_name(:last_sign_in_ip)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.username
        %td= user.password
        %td= user.admin
        %td= user.email
        %td= user.encrypted_password
        %td= user.reset_password_token
        %td= user.reset_password_sent_at
        %td= user.remember_created_at
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:password) + ':'
  %br
  = @user.password
%p
  %strong= model_class.human_attribute_name(:admin) + ':'
  %br
  = @user.admin
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'